# Generated by Django 5.0.6 on 2024-06-28 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Please enter exactly 9 digits.')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Israeli phone number. Please enter 10 digits starting with 05.', regex='^(05\\d|0[23489])\\d{7}$')])),
            ],
        ),
    ]
