# Generated by Django 5.0.6 on 2024-08-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('material', models.TextField(blank=True, help_text='Provide the material for the exam', null=True)),
                ('num_questions', models.IntegerField(blank=True, help_text='Number of questions for the exam', null=True)),
                ('max_grade', models.IntegerField(blank=True, help_text='Maximum grade for the exam', null=True)),
                ('grade', models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], help_text='Grade level for the exam', max_length=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('teacher_id', models.IntegerField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsweb.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsweb.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], max_length=1)),
                ('description', models.TextField(blank=True, help_text='Description of the subject')),
                ('syllabus', models.TextField(blank=True, help_text='Syllabus or study path for the subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='tsweb.subject')),
                ('teachers', models.ManyToManyField(help_text='Select teachers for this subject', related_name='subject_classes', to='tsweb.teacher')),
            ],
        ),
    ]
