# Generated by Django 5.0.6 on 2024-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
