# Generated by Django 5.0.6 on 2024-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0002_exam_question_subjectclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='teacher_id',
            field=models.CharField(default='213449549', max_length=9),
            preserve_default=False,
        ),
    ]
