# Generated by Django 5.0.6 on 2024-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456789, max_length=128),
            preserve_default=False,
        ),
    ]
