# Generated by Django 5.0.6 on 2024-08-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0003_alter_exam_teacher_id'),
        ('tsweb', '0003_examfeedback_studentanswer'),
    ]

    operations = [
    ]
