# Generated by Django 5.0.6 on 2024-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0004_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], default='A', help_text='Select the grade the teacher can educate', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science')], default='Math', help_text='Select the subject the teacher can teach', max_length=50),
            preserve_default=False,
        ),
    ]
