# Generated by Django 5.0.6 on 2024-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0004_merge_20240820_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
