# Generated by Django 5.0.6 on 2024-07-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0005_teacher_classes_teacher_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='Username',
        ),
    ]
