# Generated by Django 5.0.6 on 2024-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0006_rename_password_admin_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('English', 'English'), ('Geography', 'Geography'), ('Literature', 'Literature'), ('Science', 'Science')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
