# Generated by Django 5.0.6 on 2024-08-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0007_subject_remove_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default='1', help_text='Select the subject the teacher can teach', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='tsweb.subject'),
            preserve_default=False,
        ),
    ]
