# Generated by Django 5.0.6 on 2024-08-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0008_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the subject')),
                ('syllabus', models.TextField(blank=True, help_text='Syllabus or study path for the subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='tsweb.subject')),
                ('teachers', models.ManyToManyField(help_text='Select teachers for this subject', related_name='subject_classes', to='tsweb.teacher')),
            ],
        ),
    ]
