# Generated by Django 5.0.6 on 2024-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0009_subjectclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='class_name',
            field=models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], max_length=1),
        ),
    ]
