# Generated by Django 5.0.6 on 2024-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0010_alter_subjectclass_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncouragementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
