# Generated by Django 5.0.6 on 2024-08-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0011_encouragementmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('material', models.TextField(blank=True, help_text='Provide the material for the exam', null=True)),
                ('num_questions', models.IntegerField(blank=True, help_text='Number of questions for the exam', null=True)),
                ('max_grade', models.IntegerField(blank=True, help_text='Maximum grade for the exam', null=True)),
                ('test_period', models.DurationField(blank=True, help_text='Duration of the exam in the format [DD] [HH:[MM:]]ss[.uuuuuu]', null=True)),
                ('grade', models.CharField(choices=[('A', 'First grade'), ('B', 'Second grade'), ('C', 'Third grade'), ('D', 'Fourth grade'), ('E', 'Fifth grade'), ('F', 'Sixth grade')], help_text='Grade level for the exam', max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsweb.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsweb.exam')),
            ],
        ),
        migrations.DeleteModel(
            name='EncouragementMessage',
        ),
    ]
