# Generated by Django 5.0.6 on 2024-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0012_exam_question_delete_encouragementmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
