# Generated by Django 5.0.6 on 2024-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0013_question_choices_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
