# Generated by Django 5.0.6 on 2024-08-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0014_exam_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
