# Generated by Django 5.0.6 on 2024-08-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0015_question_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test_period',
        ),
    ]
