# Generated by Django 5.0.6 on 2024-08-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0016_remove_exam_test_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default='123456789', on_delete=django.db.models.deletion.CASCADE, to='tsweb.teacher'),
            preserve_default=False,
        ),
    ]
