# Generated by Django 5.0.6 on 2024-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsweb', '0018_remove_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher_id',
            field=models.IntegerField(null=True),
        ),
    ]
